### ISSUE TITLE
There's a bug

### ISSUE THREAD

**Issue by tink5** [QA-Sprint-And-Flow/test-cms-repo#13]
@tink5 there is a bug  #12 ![bitmoji](https://render.bitstrips.com/v2/cpanel/10188077-22642115_26-s1-v1.png?transparent=1&width=246)

**Comment by tink5** [comment]
#21

**Comment by danielhanold** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;5wTNqoX2&#x2F;3-build-out-custom-newsletter-system"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Build out custom newsletter system</a>
