### ISSUE TITLE
there is no chess

### ISSUE THREAD

**Issue by tink5** [QA-Sprint-And-Flow/test-cms-repo#16]
@tink5 #14 # #15

**Comment by tink5** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;p0uK8nSX&#x2F;1-1-let-s-play-a-game"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> (1) Let&#39;s Play A Game.</a>

**Comment by danielhanold** [comment]
- [ ] Item 1
- [ ] Item 2
- [ ] Item 3

**Comment by danielhanold** [comment]
Finished it!
