### ISSUE TITLE
you have mail

### ISSUE THREAD

**Issue by tink5** [QA-Sprint-And-Flow/test-cms-repo#22]
and a bug #21 @danielhanold @ #

**Comment by tink5** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;5wTNqoX2&#x2F;3-build-out-custom-newsletter-system"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Build out custom newsletter system</a>

**Comment by danielhanold** [comment]
@tink5 I don't understand your questions. Please elaborate.

**Comment by tink5** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/8133962-22642115_26-s1-v1.png?transparent=1&width=246)

**Comment by danielhanold** [comment]
Hey .. I fixed this now.

**Comment by danielhanold** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;5wTNqoX2&#x2F;3-build-out-custom-newsletter-system"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Build out custom newsletter system</a>
